name: minestom
services:
  minestom:
    container_name: minestom
    image: itzg/minecraft-server
    environment:
      TYPE: CUSTOM
      CUSTOM_SERVER: https://github.com/jirisitera/wayfare/releases/latest/download/wayfare.jar
      MEMORY: 12G
      EULA: true
      LOG_TIMESTAMP: true
      TZ: Europe/Prague
    restart: on-failure:3
    stdin_open: true
    tty: true
    networks:
      - wormhole
    volumes:
      - ./data:/data
    ports:
      - 25565:25565
networks:
  wormhole:
    name: wormhole
